### PR TITLE
Add structures from schem

### PR DESCRIPTION
**Pull request by Thorinwasher**
I made a general solution to storing the format of multiblock brewing structures. Nothing has currently been tested in this, it's just a mockup pr to show my approximate idea on this.

I made a [schem reader](https://github.com/Thorinwasher/schem) for paper that is specifically made for this purpose, hopefully it will function properly, main problem there is just that I have not published it to maven central as of yet, so it has to be  published and compiled locally for now.

Other than that, how the placed brewing structures should function performantly, is to just store the location of each part for each block in a hash map. Something like this should work:
```java
Map<WorldName, Map<BlockVector, PlacedBrewingStructure>> brewingStructures = new HashMap<>();
```

### CODE REVIEW

**Comment by Jsinco** [comment]
Very cool stuff, I appreciate this PR. I'd like Nadwey to also take a look at this PR since he's had quite a bit of work on his branch in particular.

**Comment by Thorinwasher** [comment]
Just going to note that I added a way to read structures, you have two files, one looks like this:
```json
{
    "schemFile": "something.schem",
    "origin": [0, 1, 0],
    "materialReplacements" : {
        "excludedPattern": "plank$"
        "materials": "#planks"
    }
}
```
This should conceptually do this:
1. Find the schem file in the same directory with specified name
2. Set an origin point in schem space (this is placeholder implementation)
3. Look into the material tag `minecraft:planks`, and then create a pattern to match, where the regex of the excluded pattern is removed. This is made to be able to have structures with for example one wood type. The code I made generates multiple different BreweryStructures from one set of json and schem file depending on this, if that makes sense.

**Comment by Nadwey** [comment]
> Very cool stuff, I appreciate this PR. I'd like Nadwey to also take a look at this PR since he's had quite a bit of work on his branch in particular.

Doesn't really matter since most of the work was just making the code more abstract and failing: write something, hate it, redo it, and repeat that like three times.

But for anyone curious, check the [nadwey/development](https://github.com/BreweryTeam/TheBrewingProject/tree/nadwey/development) branch.

> Other than that, how the placed brewing structures should function performantly, is to just store the location of each part for each block in a hash map. Something like this should work:
> 
> ```java
> Map<WorldName, Map<BlockVector, PlacedBrewingStructure>> brewingStructures = new HashMap<>();
> ```

This would work, but I've actually wanted to try something like [Nova's WorldDataManager](https://github.com/xenondevs/Nova/blob/main/nova/src/main/kotlin/xyz/xenondevs/nova/world/format/WorldDataManager.kt), essentially, stores the blocks in a hierarchy like this: `World -> Region -> Chunk -> Blocks` and loads and unloads the chunks when needed. (+ we could use this for everything - barrels, cauldrons, distillers, maybe sealers, something else?)

It would probably be an overkill for small servers, but big ones (especially running Folia or ShreddedPaper) might benefit from this.

I don't know if it would be a good solution and implementing it right now would probably be a waste of time, but it's something worth considering in the future IMO.

**Comment by Thorinwasher** [comment]
> This would work, but I've actually wanted to try something like [Nova's WorldDataManager](https://github.com/xenondevs/Nova/blob/main/nova/src/main/kotlin/xyz/xenondevs/nova/world/format/WorldDataManager.kt), essentially, stores the blocks in a hierarchy like this: World -> Region -> Chunk -> Blocks and loads and unloads the chunks when needed. (+ we could use this for everything - barrels, cauldrons, distillers, maybe sealers, something else?)

I think I'm against this idea, as this is not a simple shade into your plugin thing; it's its own plugin. It's therefore probably better to just imitate their implementation or something, It's just that class that we want to use anyhow.

**Comment by Nadwey** [comment]
> I think I'm against this idea, as this is not a simple shade into your plugin thing; it's its own plugin. It's therefore probably better to just imitate their implementation or something, It's just that class that we want to use anyhow.

Yeah, that's what I meant.
Sorry for the confusion

**Comment by Thorinwasher** [comment]
Meh, might as well add that into this pr

**Comment by Jsinco** [comment]
Been sort of ignoring TBP for the past month or so, going to take another look at this PR before merging

**Comment by Jsinco** [comment]
Looks good. I don't have any comments for the code itself. MockBukkit is something I want to take a good look at for testing with this project. As for the schematics, I think this is an overall good solution. Customizable barrels wouldn't really be able to be done any other way as far as I know and we were bound to end up using schematics one way or another. I'm happy that we can use a smaller, more lightweight schematic reader than something like WorldEdit. 

I'm going to go ahead and merge these commits. We can make any needed edits later on.

**Pull request merged**
